export const VAULT_NAME = 'guild-scrabble-keyvault';
export const VAULT_URL = `https://${VAULT_NAME}.vault.azure.net`;
export const DB_SECRET_NAME = 'cdbsecret';
export const DB_NAME = 'GuildScrabbleDB';
export const DB_URL = 'https://guild-scrabble-cosmodb-api.documents.azure.com:443/';
export const CONTAINER_NAME = 'games';
export const COMPLETE_GAME_PRUNE_HOURS = 24; //Hours to keep complete games prior to pruning.
export const INACTIVE_GAME_PRUNE_HOURS = 7 * 24; //Abandon game cleanup time
export const PRUNE_DB_HOURS = 12; //hours between executions of the DB pruning logic

export const CERT_AGE = 300; // seconds to trust jwks key prior to checking for new one.

export const BLANK_GRID = [
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
];

export const BLANK_TILERACK = ['', '', '', '', '', '', ''];

export const tiles: string[] = [
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'B',
  'B',
  'C',
  'C',
  'D',
  'D',
  'D',
  'D',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'F',
  'F',
  'G',
  'G',
  'G',
  'H',
  'H',
  'I',
  'I',
  'I',
  'I',
  'I',
  'I',
  'I',
  'I',
  'I',
  'J',
  'K',
  'L',
  'L',
  'L',
  'L',
  'M',
  'M',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'P',
  'P',
  'Q',
  'R',
  'R',
  'R',
  'R',
  'R',
  'R',
  'S',
  'S',
  'S',
  'S',
  'T',
  'T',
  'T',
  'T',
  'T',
  'T',
  'U',
  'U',
  'U',
  'U',
  'V',
  'V',
  'W',
  'W',
  'X',
  'Y',
  'Y',
  'Z',
  '?',
  '?',
];
